name: 'GitHub Dotnet Action'
run-name: .NET Action- ${{github.run_id}}
on:   
   workflow_dispatch:
jobs:   
     test-job:
            runs-on: ubuntu-latest
            permissions:
              contents: read
              pull-requests: read
            steps:         
                 - name: Hello
                   run: | 
                      docker builder prune
                 - name: .NET Action Demo       
                   id: dotnet-code-metrics         
                   uses: kamil467/github_action_dotnet@main     
                   env:   
                      GITHUB_REPO_READ_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                   with:
                      release: 'releasev1.0.1'
                 - name: Print Summary
                   run: |
                      cat release-summary.md >> $GITHUB_STEP_SUMMARY
