name: 'GitHub Dotnet Action'
run-name: .NET Action- ${{github.run_id}}
on:   
   workflow_dispatch:
jobs:   
     test-job:
            runs-on: ubuntu-latest
            steps:         
                 - name: Hello
                   run: | 
                      docker builder prune
                 - name: .NET Action Demo       
                   id: dotnet-code-metrics         
                   uses: kamil467/github_action_dotnet@main     
                   env:   
                      GREETINGS: 'Hello, .NET developers!' 
                   with:
                   
                     owner: 'ABC'
                     release: 'phase2'
                 - name: Print Summary
                   run: |
                      cat release.md >> $GITHUB_STEP_SUMMARY
