name: 'GitHub Dotnet Action'
run-name: .NET Action- ${{github.run_id}}
on:   
   workflow_dispatch:
jobs:   
     test-job:
            runs-on: ubuntu-latest
            steps:         
                 - name: Hello
                   run: | 
                     echo 'testing dotnet action'     
                 - name: .NET code metrics        
                   id: dotnet-code-metrics         
                   uses: kamil467/github_action_dotnet@main     
                   env:   
                      GREETINGS: 'Hello, .NET developers!' 
                   with:
                   
                     owner: 'mohamed kamil hussain'
