name: Build and Deploy Main Branch
run-name: Release - ${{inputs.version}} 
on:
 workflow_call:
  inputs:
    version:
        type: string
        required: true
jobs:
   build:
     runs-on: ubuntu-latest
     
     steps:
         - name: test run
           run : |
              echo ${{inputs.version}}
