name: 'Reusable Workflow'
on:
 workflow_call:
   secrets:
    config-value:
       required: false
       
jobs:
 reusable-job:
   runs-on: ubuntu-latest
   steps:
      - name: test-step
        run: |
          echo "reusable workflow: ${{secrets.config-value}}"
