name: Status Check
on:
  workflow_dispatch:
  pull_request:
   branches:
      - main
jobs:
 status-job:
   runs-on: ubuntu-latest
   steps:
     - name: test step
       run: |
        echo "Hi Kamil"
