name: 'Test Resuable Workflow'
run-name: Test Run -  ${{github.run_id}} 
on: 
  workflow_dispatch:
jobs:
   test-job:
       permissions:
          contents: read
          id-token: write
       runs-on: ubuntu-latest 
       steps:
        - name: Hello world action step
          id: hello
          uses: kamil467/demo-github-action@main
          with:
             release-name: release1.0
        - name: Print Person file
          run: cat person.md >> $GITHUB_STEP_SUMMARY
        
              
