name: 'Test Resuable Workflow'
on: 
  workflow_dispatch:
jobs:
   test-job:
       runs-on: ubuntu-latest
       steps:
           - name: Test action
             run: |
              echo "hello world"
              
