name: Version Test
run-name: Release Version - (( ${{vars.BUILD_VERSION}} + 1 ))
on:
 workflow_dispatch:

jobs:

 updateversionnumber:
  runs-on: ubuntu-latest
  
  steps:
     - name: Update release number
       run: |
        $ver=[int]${{vars.BUILD_VERSION}}
        $ver = $ver+1
        $env:GITHUB_ENV=$ver
        echo $ver
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: list of files
       run: |
          ls
       shell: pwsh
       
     - name: Update Version Number
       run: |
        $majorversion=(Get-Item -Path version.txt | Get-Content -First 1)
        echo $majorversion
        $minorVersion=(Get-Item -Path version.txt | Get-Content -TotalCount 2)[-1]
        echo $minorVersion
        $patch=(Get-Item -Path version.txt | Get-Content -Tail 1)
        echo $patch
        $patchNumber = $patch.split("=")
        echo $patchNumber[0]
        echo $patchNumber[1]
        $patchVersionInt =[int]$patchNumber[1]
        echo $patchVersionInt
        $patchVersion = $patchVersionInt+1
        echo $patchVersion
        $filecontent = Get-Content -Path version.txt
        $filecontent[2]= "PATCH="+$patchVersion
        Set-Content -Path version.txt -Value $filecontent
       shell: pwsh
       
     - name: Commit Patch Version
       run: |
         git pull origin main
         git add version.txt
         git config --global user.name "kamil hussain"
         git config --global user.email "youremail@yourdomain.com"
         git commit -m "My commit message"
         git push
      
         
 callmainworkflow:
            needs:  updateversionnumber
            uses: kamil467/devops-playground/.github/workflows/main-test.yml@main
            with:
             version: 1.0.34
             
