name: Version Test
on:
 workflow_dispatch:

jobs:
 updateversionnumber:
  runs-on: ubuntu-latest
  steps:
     - name: Checkout
       uses: actions/checkout@v2.7.0
     - name: list of files
       run: |
        echo get-childitem -path
       shell: pwsh
       
     - name: Update Version Number
       run: |
        $version=(Get-Item -Path .version.txt | Get-Content -First 1)
        $version
        $splitVersion = $version.split('.')
        echo $splitVersion
       shell: pwsh
  
