name: Version Test
on:
 workflow_dispatch:

jobs:
 updateversionnumber:
  runs-on: ubuntu-latest
  steps:
     - name: Checkout
       uses: actions/checkout@v2.7.0
     - name: list of files
       run: |
          ls
       shell: pwsh
       
     - name: Update Version Number
       run: |
        $majorversion=(Get-Item -Path version.txt | Get-Content -First 1)
        echo $majorversion
        $minorVersion=(Get-Item -Path version.txt | Get-Content -TotalCount 2)[-1]
        echo $minorVersion
        $patch=(Get-Item -Path version.txt | Get-Content -Tail 1)
        echo $patch
        $patchNumber = $patch.split("=")
        echo $patchNumber[0]
        echo $patchNumber[1]
        echo $patchNumber[2]
        echo $patchNumber
       shell: pwsh
  
